[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/functions"

[[redirects]]
  from = "/api-docs/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  directory = "dist/functions"
  node_bundler = "esbuild" 